Relax the upper limit on numerical errors in projection calculation tests
In projection calculation tests on Linux (Ubuntu, `x64_64`), numerical
errors relative to PROJ$B!G(Bs output values reach the upper limit as
follows:

```
thread 'projection::lcc::tests::agrees_with_proj_for_spherical_secant_cone' (9465) panicked at src/projection/lcc.rs:292:9:
actual (37751204.131035715, -18401452.34648599) differs from expected (37751204.131035715, -18401452.34648598) by more than 0.00000001
```

This test passes on macOS and Windows.
Therefore, the cause is likely differences in floating-point arithmetic
across platforms, particularly differences in library implementations.

Since an error of `1.0e-7` meters is sufficient for practical accuracy,
I will relax the numerical error limit here.