cli: fix a runtime error due to unsupported regex syntax
The error is as follows:

```
thread 'main' panicked at cli/src/commands/dump.rs:67:10:
called `Result::unwrap()` on an `Err` value: Syntax(
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
regex parse error:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1: (?x)                    # insignificant whitespace mode
2:             ^
3:             (?<pos>[0-9]+(-[0-9]+)?)  # octet position
                 ^
4:             (?<param>\s+\S+\s+)       # parameter
5:             (?<equal>=)
6:             (?<val>\s+.+\s+?)         # value
7:             (?<comment>(//.+)?)       # description
8:             $
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: unrecognized flag
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
)
```

Named captures `(?<name>re)` is supported from regex 1.8.0.
Before that, they had to be written as `(?P<name>re)`.